### ISSUE TITLE
Unable to switch the encoding

### ISSUE THREAD

**Issue by 50Wliu** [atom/encoding-selector#48]
_From @irudoy on May 17, 2017 6:21_

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since version 1.17.0 switching encoding to Windows 1251 working incorrectly. Selected encoding changes in the status bar, but cyrillic characters still ���.
 
Also, I have an error in the console: `TypeError: iconv.decodeStream is not a function`.

### Steps to Reproduce

1. Create file with contents: `абвгдеёжзфывапролджэ`
2. Save file and close
3. Re-open file in the Atom
4. Select Windows 1251 encoding

**Expected behavior:** `абвгдеёжзфывапролджэ`

**Actual behavior:** `���������`

**Reproduces how often:** always

### Versions

1.17.0
1.18.0 beta

_Copied from original issue: atom/atom#14438_

**Comment by 50Wliu** [comment]
_From @pluto1019 on May 17, 2017 7:24_

please~~ same problem~~
my file encoding 'euc-kr' same problem~
not change~

**Comment by xxchaxx** [comment]
I am suffering from the same problem.
Even if you specify all other encodings, not just "euc-jp" that I use, it has no effect.
The OS is Windows 7 x86_64, and the version of ATOM is 1.17.0.

**Comment by 50Wliu** [comment]
Full stack trace:
```
Uncaught (in promise) TypeError: iconv.decodeStream is not a function
    at File.module.exports.File.createReadStream (C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app\node_modules\pathwatcher\lib\file.js:345:1)
    at C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app\node_modules\pathwatcher\lib\file.js:309:1
    at File.module.exports.File.read (C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app\node_modules\pathwatcher\lib\file.js:305:1)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app\node_modules\text-buffer\lib\text-buffer.js:1182:1)
    at TextBuffer.module.exports.TextBuffer.setEncoding (C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app\node_modules\text-buffer\lib\text-buffer.js:353:1)
    at TextEditor.module.exports.TextEditor.setEncoding (C:\Users\user\AppData\Local\Atom x64\app-dev\resources\app\src\text-editor.js:983:1)
    at Object.didConfirmSelection (file:///C:/Users/user/Documents/GitHub/encoding-selector/lib/encoding-list-view.js:29:48)
    at SelectListView.confirmSelection (C:\Users\user\Documents\GitHub\encoding-selector\node_modules\atom-select-list\src\select-list-view.js:296:20)
    at SelectListView.didClickItem (C:\Users\user\Documents\GitHub\encoding-selector\node_modules\atom-select-list\src\select-list-view.js:211:10)
    at ListItemView.onclick (C:\Users\user\Documents\GitHub\encoding-selector\node_modules\atom-select-list\src\select-list-view.js:151:31)
    at ListItemView.didClick (C:\Users\user\Documents\GitHub\encoding-selector\node_modules\atom-select-list\src\select-list-view.js:344:10)
```

**Comment by jonassdp** [comment]
Looks like the error is not happening in dev-mode... Can anyone confirm?

**Comment by 50Wliu** [comment]
@jonassdp Confirmed.  That's really weird.

**Comment by ikari7789** [comment]
I just noticed it isn't happening in dev mode neither.

**Comment by xxchaxx** [comment]
Full stack trace:
[code]
init.coffee:31 Uncaught (in promise) TypeError: iconv.decodeStream is not a function
    at File.module.exports.File.createReadStream (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:345:1)
    at C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:309:1
    at File.module.exports.File.read (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:305:1)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1180:1)
    at TextBuffer.module.exports.TextBuffer.setEncoding (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:352:1)
    at TextEditor.module.exports.TextEditor.setEncoding (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\src\text-editor.js:908:1)
    at file:///C:/Users/user/.atom/init.coffee:31:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
    module.exports.File.createReadStream @ <embedded>:104507
    (anonymous function) @ <embedded>:104471
    module.exports.File.read @ <embedded>:104467
    module.exports.TextBuffer.updateCachedDiskContents @ <embedded>:28499
    module.exports.TextBuffer.setEncoding @ <embedded>:27671
    module.exports.TextEditor.setEncoding @ <embedded>:3127
    (anonymous function) @ init.coffee:31
    readFileAfterClose @ fs.js:445
[/code]

**Comment by xxchaxx** [comment]
```Full stack trace
init.coffee:31 Uncaught (in promise) TypeError: iconv.decodeStream is not a function
    at File.module.exports.File.createReadStream (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:345:1)
    at C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:309:1
    at File.module.exports.File.read (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\pathwatcher\lib\file.js:305:1)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1180:1)
    at TextBuffer.module.exports.TextBuffer.setEncoding (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:352:1)
    at TextEditor.module.exports.TextEditor.setEncoding (C:\Users\user\AppData\Local\atom\app-1.17.0\resources\app\src\text-editor.js:908:1)
    at file:///C:/Users/user/.atom/init.coffee:31:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
    module.exports.File.createReadStream @ <embedded>:104507
    (anonymous function) @ <embedded>:104471
    module.exports.File.read @ <embedded>:104467
    module.exports.TextBuffer.updateCachedDiskContents @ <embedded>:28499
    module.exports.TextBuffer.setEncoding @ <embedded>:27671
    module.exports.TextEditor.setEncoding @ <embedded>:3127
    (anonymous function) @ init.coffee:31
    readFileAfterClose @ fs.js:445
```

**Comment by pistou** [comment]
I have the same kind of issue: I have `ISO-8859-15` encoded files and when I reload them they are in `UTF-8`
`dev-mode` seems to work well indeed.

**Comment by Daidalos117** [comment]
Same problem here, in 1.16 it was ok. Now switch doesnt work. Even when another encoding is set as default, file is still opened as "UTF-8".

**Comment by Double-Luo** [comment]
Same problem here.I have to back the Atom‘s version to 1.12.7 ,that was my first install the Atom's Package。I see it was work well。

**Comment by Bargamut** [comment]
Same issue. But it works fine in Dev Mode.
So, what the difference between these? )

**Comment by FluidCoding** [comment]
Same issue with Windows 1252, no abnormal characters just complying with existing code-base.

> Unable to read file after file change event. Make sure you have permission to access [] iconv.decodeStream is not a function

**Comment by iolsen** [comment]
cc @as-cii

**Comment by gabrielhermel** [comment]
Not getting the "is not a function" errors anymore, but characters are still ���.

**Comment by Bargamut** [comment]
Now it's fixed!
Thanks! ))

**Comment by SquawkWoof** [comment]
Just upgraded to 1.28.0 and having the same problem.  Changing the encoding does apply the encoding to the file, *ever*.

eg.:
`open file encoded as utf-8 > change encoding to windows-1252 > save > reopen file > file is still utf-8`

It's extremely frustrating.
